name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: xcodebuild -project "No Nonsense Sports.xcodeproj" -scheme "No Nonsense Sports" -destination "platform=iOS Simulator,name=iPhone 16" build

      - name: Test
        run: xcodebuild test -project "No Nonsense Sports.xcodeproj" -scheme "No Nonsense Sports" -destination "platform=iOS Simulator,name=iPhone 16"
